(define (main)
    (display (+ 3 5))
    (newline)
    (display (- 10 7))
    (newline)
    (display (* 6 7))
    (newline)
    (display (/ 20 4))
    (newline)
    (display (mod 10 3))
    (newline)
    (display (< 5 10))
    (newline)
    (display (< 10 5))
    (newline)
    (display (>= 10 10))
    (newline)
    (display (= 4 4))
    (newline)
    (display (<> 4 4))
    (newline)
)